### ISSUE TITLE
last update 2 years ago?

### ISSUE THREAD

**Issue by k1ng440** [CaptainUp/captainup-nodejs#1]

**Comment by Radagaisus** [comment]
Hi @k1ng440,

Since the Node.js SDK is a pretty straightforward wrapper around the Captain Up API – simply taking care of sending the requests and parsing the responses – there isn't really much to update. You can see a live demo of the SDK at: http://nodejs.captainup.com.

If you have any questions or encounter any issues during integration, please open a follow up issue or contact us directly at team@captainup.com.
